config/routes.rb
MyTimeline::Application.routes.draw do

  

  get "tweeting/index"
  get "tweets/index"
  get "tweets/timeline"
 get "tweets/create"
  post "tweets/search"
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match '/auth/failure', to: redirect('/') , via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  root 'tweets#new'

resources :tweets, only: [:new, :create, :timeline, :search]
resources :sessions, only: [:create, :destroy]
resource :welcome, only: [:show]

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  
  #A method to grab latest tweets from Twitter
  def self.get_latest_new_year_resolution_tweets
    
    #create a Twitter Search object
    search = Twitter::Search.new
    
    #grab recent 100 tweets which contain 'indie' words, and loop each of them
    search.containing("indie").result_type("recent").per_page(100).fetch.each do |tweet_results|
      
      #parsing the string 'created_at' to DateTime object
      twitter_created_at = DateTime.parse(tweet_results.created_at)
      
      #making sure we are not saving exact same tweet from a person again 
      unless Tweet.exists?(['twitter_created_at = ? AND from_user_id_str = ?', DateTime.parse(tweet_results.created_at), tweet_results.from_user_id_str])
      
        #finally creating the tweet record
        Tweet.create!({
            :from_user => tweet_results.from_user,
            :from_user_id_str => tweet_results.from_user_id_str,
            :profile_image_url => tweet_results.profile_image_url,
            :text => tweet_results.text,
            :twitter_created_at => twitter_created_at
        })
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
   # This method, from_omniauth, takes and parses out data passed back by omniauth

 def self.from_omniauth(auth)
where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
user.provider = auth.provider
user.uid = auth.uid
user.name = auth.info.name
user.oauth_token = auth.credentials.token
user.oauth_secret = auth.credentials.secret
user.save!
end
end
	#To Send the Tweets
	def tweet(tweet)
		client = Twitter::REST::Client.new do |config|
		config.consumer_key = Rails.application.config.twitter_key
		config.consumer_secret = Rails.application.config.twitter_secret
		config.access_token = oauth_token
		config.access_token_secret = oauth_secret
	end
	client.update(tweet)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private

  #current_user will return current logged in user in @current_user var.

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  #make current_user mthod as helper method so that View can use it.

  helper_method :current_user



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
	
end

# Create Methot will allow to take the data passed by omniauth,
# & find or create the user that omniauth returns 
# and then store that user's id in the session

def create
user = User.from_omniauth(env["omniauth.auth"])
session[:user_id] = user.id
redirect_to root_url, notice: "Signed in!"
end

# To Log Out the User

def destroy
session[:user_id] = nil
redirect_to root_url, notice: "Signed out!"
end

end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController
end

app/controllers/tweeting_controller.rb
def index
    #Get the tweets (records) from the model Ordered by 'twitter_created_at' descending
    @tweeting = Tweet.order("twitter_created_at desc") 
    @tweeting = Post.all   
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_filter :homeTimeline

  def new
  end
#The create method will take input from the user and use that information to send a tweet
#current_user method is defined in application controller.
#Pass the message to tweet method of user.rb >> Tweet Method will pass it to client.update
  def create
  	current_user.tweet(twitter_params[:message])
  end

  def twitter_params
  	params.require(:tweet).permit(:message)
  end


  def create_retweet
  	current_user.retweet(rt_params[:id])
  	
  end

  def rt
  	params.require(:retweet).permit(:id)
  end
 

  def search
  	@temp = params[:search]
  	
  	@result = @client.search(@temp)


  
     
      
    

  

  end



  def homeTimeline


  		@homeNewsFeed = []
  		

		@client = Twitter::REST::Client.new do |config|
		config.consumer_key = "HoVab6MwmTklrqD1J4Bw3A"
		config.consumer_secret = "1muXZ3UV0HKY8W3zc0Go9g1vhmXsfTopSzYujyyNTw"

		if current_user.nil? 
			config.access_token ="54292452-QPFHB62vk7HzkFz2IqfQjMopjLo5p6dZGnmUuRchE"
		else
		config.access_token = current_user.oauth_token
		config.access_token_secret = current_user.oauth_secret

		end

	end
		if !current_user.nil? 
		@tweetURIs = []
		@homeTimeline = @client.user_timeline
		#@tweetURIs << @homeTimeline.twuri
		@homeNewsFeed = @client.home_timeline
		end	
	end

	def retweet(id)
		
		@client = Twitter::REST::Client.new do |config|
		config.consumer_key = "HoVab6MwmTklrqD1J4Bw3A"
		config.consumer_secret = "1muXZ3UV0HKY8W3zc0Go9g1vhmXsfTopSzYujyyNTw"
		config.access_token = "54292452-QPFHB62vk7HzkFz2IqfQjMopjLo5p6dZGnmUuRchE"
		config.access_token_secret = "XqW0gM7RFHMz6u718MIblCjZ9PODnT255T8tTMDwj85Y8"
	end
	@client.retweet(id)
	end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def show
		
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/soundcloud_helper.rb
module SoundcloudHelper
end

app/helpers/tweeting_helper.rb
module TweetingHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tweets/create.html.erb
    <h1>Success!</h1>
    <p>Your tweet has been sent!</p>
    <%= link_to "Would you like to send another?", new_tweet_path %>

app/views/tweets/new.html.erb
<style type="text/css">
table {
  width: 100%;
  border: 1px solid white;
  text-align: left; }
th {
  font-weight: bold;
  background-color: #9FB6CD;
  border-bottom: 1px solid white; }
td,th {
  padding: 4px 5px; }
  .scrollable {
                height: 495px;
                overflow: auto;
            }
  .scrollable1 {
      height: 456px;
      overflow: auto;
    }
    .recorderUI{
      text-align: center;
      width: 100%;

    
    }

  .span2{
    text-align: center;
  }
  .tweets {

    padding-left: 2%;
    padding-top: 50px;
    padding-right: 2%;
    padding-bottom: 2%;
    font-family: Century Gothic;
  }

.odd {
  background-color: #def; }
.odd td {
  border-bottom: 1px solid #cef; }
  /*DARKEN*/
.brighten img {
  -webkit-filter: brightness(100%);
  -webkit-transition: all 0.1s ease;
     -moz-transition: all 0.1s ease;
       -o-transition: all 0.1s ease;
      -ms-transition: all 0.1s ease;
          transition: all 0.1s ease;
}
 
.brighten img:hover {
  -webkit-filter: brightness(95%);

}
}


  </style>


<div class="container">


        <div class="row">
          <div class="span5">
            <div class="well bs-component">
              <fieldset>
                <% if current_user %>
     <div class = "span2">
      <div class="brighten pic">
      <%= link_to image_tag('mytweets.png') , tweets_timeline_path %>
     
    </div>
    </div>




    <div class ="span2">
       <div class="brighten pic">
         <%= link_to image_tag('newsfeed.png') , new_tweet_path %>
      
    </div>
    </div>
    <% end %>
    

        <div class="tweets"><br />
            
          <div class="tweet_text_area">

            <div class="tweet_text">
              <div class = "scrollable">
              <% if current_user %>
                <table>
                  <tr>
                    <th><h3>Users</h3></th>
                    <th><h3>Tweets</h3></th>
                  </tr>
                  
                

                  <% @homeNewsFeed.each do |t| %>

                  
        

                  <tr>


                    <th><img src= "<%= t.user.profile_image_url %>" /></th>
                    <th><%= t.text %>

                      <%= t.id %>
                      <div> <%= link_to "Retweet" %>  <%=link_to image_tag("retweet.png", :border => 0)  %> <%=link_to " Reply " %><%=link_to image_tag("mail_reply_all-512.png", :border => 0) %></div></th>


                  </tr>
                  
                  

                  <% end %>
                  <% else %>

                  
                    <br /> <br />
                    <%=image_tag("twitterLogo.png", :border => 0)%>
                   </div>
                   <% end %>
              </div>
            </div>



                </table>

               </div>


                </fieldset>
            </div>
          </div>
          <div class="span4">
            <div class="well bs-component">
              <fieldset>
                
                <h3>SoundCloud Indie Player</h3>
             
               <div class="tweets">

                <div id="putTheWidgetHere"></div>
                <% if current_user %>
                 <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?visual=true&url=http%3A%2F%2Fapi.soundcloud.com%2Fgroups%2F10037&show_artwork=true&client_id=0d75d3de661d91b3616b291ea5e82abe"></iframe>
                 
                  <% else %>
                  <div class = "scrollable1">
                  
                    <%=image_tag("soundcloudLogo.png", :border => 0)%>
                  </div>
                  </div>

                  <% end %>           
               
                </fieldset>
            </div>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">

              <% if current_user %>
                Signed in as  <em><%= current_user.name %>!</em>
                  <div>


                  <%= link_to " Sign out ", signout_path, id: "sign_out" %></div>
        
                  <% else %>
                   <div class="brighten pic">

                  <%= link_to image_tag('twitter.png') , "/auth/twitter", id: "sign_in" %>
                  </div>
                  
                  <% end %>

            </div>
          </div>
          <div class="span3">
            <div clas= "soundcloud">
            <div class="well sidebar-nav">
           
              <% if current_user.nil? %>
                 <%=image_tag("logintotweet.png", :border => 0)%>


             <% else %>
             <br 
              <ul class="nav nav-list">
                <%= form_for :tweet, url: tweets_path, remote:true,  method: :post do |f| %>
                <%= f.text_area :message , :maxlength => 140 %>
                <!--%= f.text_area :message, :maxlenght => 40 %-->

                   
                  <div class="brighten pic">
                  <%= image_submit_tag ('tweet-button.png') %>

                   </div>

                 
                    <% end %>

               <% end %>

              </ul>
            </div><!--/.well -->



            </div>
    



            <div class="well sidebar-nav">
              <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="//connect.soundcloud.com/sdk.js"></script>
<script>
  SC.initialize({
    client_id: "c202b469a633a7a5b15c9e10b5272b78",
    redirect_uri: "http://connect.soundcloud.com/examples/callback.html"
  });

  $("#recorderUI.reset #controlButton").live("click", function(e){
    updateTimer(0);
    SC.record({
      start: function(){
        setRecorderUIState("recording");
      },
      progress: function(ms, avgPeak){
        updateTimer(ms);
      }
    });
    e.preventDefault();
  });

  $("#recorderUI.recording #controlButton, #recorderUI.playing #controlButton").live("click", function(e){
    setRecorderUIState("recorded");
    SC.recordStop();
    e.preventDefault();
  });

  $("#recorderUI.recorded #controlButton").live("click", function(e){
    updateTimer(0);
    setRecorderUIState("playing");
    SC.recordPlay({
      progress: function(ms){
        updateTimer(ms);
      },
      finished: function(){
        setRecorderUIState("recorded");
      }
    });
    e.preventDefault();
  });

  $("#reset").live("click", function(e){
    SC.recordStop();
    setRecorderUIState("reset");
    e.preventDefault();
  });

  $("#upload").live("click", function(e){
    setRecorderUIState("uploading");

    SC.connect({
      connected: function(){
        $("#uploadStatus").html("Uploading...");
        SC.recordUpload({
          track: {
            title: "Untitled Recording",
            sharing: "private"
          }
        }, function(track){
          $("#uploadStatus").html("Uploaded: <a href='" + track.permalink_url + "'>" + track.permalink_url + "</a>");
        });
      }
    });

    e.preventDefault();
  });

  function updateTimer(ms){
    $("#timer").text(SC.Helper.millisecondsToHMS(ms));
  }

  function setRecorderUIState(state){
    // state can be reset, recording, recorded, playing, uploading
    // visibility of buttons is managed via CSS
    $("#recorderUI").attr("class", state);
  }
</script>

<div id="recorderUI" class="reset">
  <a href="#" id="controlButton" class="record"><span id="timer" class="hidden">0:00</span></a>
  <div id="otherControls">
    <a href="#" id="reset" class="button">Reset</a>
    <a href="#" id="upload" class="button">Upload</a>
  </div>
  <div id="uploadStatus"></div>
</div>


            
            </div><!--/.well -->
         <div class="well sidebar-nav">
              <h3>playlist</h3>
              </ul>
            </div><!--/.well -->
      </div><!--/span-->
 
       </div>
          

    

app/views/tweets/search.html.erb
<style type="text/css">
table {
  width: 100%;
  border: 1px solid white;
  text-align: left; }
th {
  font-weight: bold;
  background-color: #9FB6CD;
  border-bottom: 1px solid white; }
td,th {
  padding: 4px 5px; }
  .scrollable {
                height: 495px;
                overflow: auto;
            }
  .scrollable1 {
      height: 456px;
      overflow: auto;
    }
    .recorderUI{
      text-align: center;
      width: 100%;

    
    }

  .span2{
    text-align: center;
  }
  .tweets {

    padding-left: 2%;
    padding-top: 50px;
    padding-right: 2%;
    padding-bottom: 2%;
    font-family: Century Gothic;
  }

.odd {
  background-color: #def; }
.odd td {
  border-bottom: 1px solid #cef; }
  /*DARKEN*/
.brighten img {
  -webkit-filter: brightness(100%);
  -webkit-transition: all 0.1s ease;
     -moz-transition: all 0.1s ease;
       -o-transition: all 0.1s ease;
      -ms-transition: all 0.1s ease;
          transition: all 0.1s ease;
}
 
.brighten img:hover {
  -webkit-filter: brightness(95%);

}
}


  </style>


<div class="container">


        <div class="row">
          <div class="span5">
            <div class="well bs-component">
              <fieldset>
                <% if current_user %>
     <div class = "span2">
      <div class="brighten pic">
      <%= link_to image_tag('mytweets.png') , tweets_timeline_path %>
     
    </div>
    </div>




    <div class ="span2">
       <div class="brighten pic">
         <%= link_to image_tag('newsfeed.png') , new_tweet_path %>
      
    </div>
    </div>
    <% end %>
    

        <div class="tweets"><br />
            
          <div class="tweet_text_area">

            <div class="tweet_text">
              <div class = "scrollable">
              <% if current_user %>
                <table>
                  <tr>
                    <th><h3>Users</h3></th>
                    <th><h3>Tweets</h3></th>
                    </tr>
						          <% @result.each do |t|%>
                    <tr>
                    <th><img src= "<%= t.user.profile_image_url %>" /></th>
                    <th><%= t.text %>
                      <a href="https://twitter.com/twitterapi" class="twitter-follow-button" data-show-count="false" data-lang="en">Follow</a>
                      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
                    </th>
                  </tr>
                  
                  

                  <% end %>
                  <% else %>

                  
                    <br /> <br />
                    <%=image_tag("twitterLogo.png", :border => 0)%>
                   </div>
                   <% end %>
              </div>
            </div>
                </table>

               </div>


                </fieldset>
            </div>
          </div>
          <div class="span4">
            <div class="well bs-component">
              <fieldset>
                
                <h3>SoundCloud Indie Player</h3>
             
               <div class="tweets">

                <div id="putTheWidgetHere"></div>
                <% if current_user %>
                 <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?visual=true&url=http%3A%2F%2Fapi.soundcloud.com%2Fgroups%2F10037&show_artwork=true&client_id=0d75d3de661d91b3616b291ea5e82abe"></iframe>
                 
                  <% else %>
                  <div class = "scrollable1">
                  
                    <%=image_tag("soundcloudLogo.png", :border => 0)%>
                  </div>
                  </div>

                  <% end %>           
               
                </fieldset>
            </div>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">

              <% if current_user %>
                Signed in as  <em><%= current_user.name %>!</em>
                  <div>


                  <%= link_to " Sign out ", signout_path, id: "sign_out" %></div>
        
                  <% else %>
                   <div class="brighten pic">

                  <%= link_to image_tag('twitter.png') , "/auth/twitter", id: "sign_in" %>
                  </div>
                  
                  <% end %>

            </div>
          </div>
          <div class="span3">
            <div clas= "soundcloud">
            <div class="well sidebar-nav">
           
              <% if current_user.nil? %>
                 <%=image_tag("logintotweet.png", :border => 0)%>


             <% else %>
             <br 
              <ul class="nav nav-list">
                <%= form_for :tweet, url: tweets_path, remote:true,  method: :post do |f| %>
                <%= f.text_area :message , :maxlength => 140 %>
                <!--%= f.text_area :message, :maxlenght => 40 %-->

                   
                  <div class="brighten pic">
                  <%= image_submit_tag ('tweet-button.png') %>

                   </div>

                 
                    <% end %>

               <% end %>

              </ul>
            </div><!--/.well -->



            </div>
    



            <div class="well sidebar-nav">
              
                

            
            </div><!--/.well -->
         <div class="well sidebar-nav">
              <h3>playlist</h3>
              </ul>
            </div><!--/.well -->
      </div><!--/span-->
 
       </div>
          

    

app/views/tweets/timeline.html.erb
<style type="text/css">
table {
  width: 100%;
  border: 1px solid white;
  text-align: left; }
th {
  font-weight: bold;
  background-color: #9FB6CD;
  border-bottom: 1px solid white; }
td,th {
  padding: 4px 5px; }
  .scrollable {
                height: 495px;
                overflow: auto;
            }
  .scrollable1 {
      height: 456px;
      overflow: auto;
    }
    .recorderUI{
      text-align: center;
      width: 100%;

    
    }

  .span2{
    text-align: center;
  }
  .tweets {

    padding-left: 2%;
    padding-top: 50px;
    padding-right: 2%;
    padding-bottom: 2%;
    font-family: Century Gothic;
  }

.odd {
  background-color: #def; }
.odd td {
  border-bottom: 1px solid #cef; }
  /*DARKEN*/
.brighten img {
  -webkit-filter: brightness(100%);
  -webkit-transition: all 0.1s ease;
     -moz-transition: all 0.1s ease;
       -o-transition: all 0.1s ease;
      -ms-transition: all 0.1s ease;
          transition: all 0.1s ease;
}
 
.brighten img:hover {
  -webkit-filter: brightness(95%);

}
}


  </style>


<div class="container">


        <div class="row">
          <div class="span5">
            <div class="well bs-component">
              <fieldset>
                <% if current_user %>
     <div class = "span2">
      <div class="brighten pic">
      <%= link_to image_tag('mytweets.png') , tweets_timeline_path %>
     
    </div>
    </div>




    <div class ="span2">
       <div class="brighten pic">
         <%= link_to image_tag('newsfeed.png') , new_tweet_path %>
      
    </div>
    </div>
    <% end %>
    

        <div class="tweets"><br />
            
          <div class="tweet_text_area">

            <div class="tweet_text">
              <div class = "scrollable">
              <% if current_user %>
                <table>
                  <tr>
                    <th><h3>Users</h3></th>
                    <th><h3>Tweets</h3></th>
                  </tr>
                  
                

                  <% @homeTimeline.each do |t| %>

                  
        

                  <tr>


                    <th><img src= "<%= t.user.profile_image_url %>" /></th>
                    <th><%= t.text %>

                      <%= t.id %>
                      <div> <%= link_to "Retweet" %>  <%=link_to image_tag("retweet.png", :border => 0)  %> <%=link_to " Reply " %><%=link_to image_tag("mail_reply_all-512.png", :border => 0) %></div></th>


                  </tr>
                  
                  

                  <% end %>
                  <% else %>

                  
                    <br /> <br />
                    <%=image_tag("twitterLogo.png", :border => 0)%>
                   </div>
                   <% end %>
              </div>
            </div>



                </table>

               </div>


                </fieldset>
            </div>
          </div>
          <div class="span4">
            <div class="well bs-component">
              <fieldset>
                
                <h3>SoundCloud Indie Player</h3>
             
               <div class="tweets">

                <div id="putTheWidgetHere"></div>
                <% if current_user %>
                 <iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?visual=true&url=http%3A%2F%2Fapi.soundcloud.com%2Fgroups%2F10037&show_artwork=true&client_id=0d75d3de661d91b3616b291ea5e82abe"></iframe>
                 
                  <% else %>
                  <div class = "scrollable1">
                  
                    <%=image_tag("soundcloudLogo.png", :border => 0)%>
                  </div>
                  </div>

                  <% end %>           
               
                </fieldset>
            </div>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">

              <% if current_user %>
                Signed in as  <em><%= current_user.name %>!</em>
                  <div>


                  <%= link_to " Sign out ", signout_path, id: "sign_out" %></div>
        
                  <% else %>
                   <div class="brighten pic">

                  <%= link_to image_tag('twitter.png') , "/auth/twitter", id: "sign_in" %>
                  </div>
                  
                  <% end %>

            </div>
          </div>
          <div class="span3">
            <div clas= "soundcloud">
            <div class="well sidebar-nav">
           
              <% if current_user.nil? %>
                 <%=image_tag("logintotweet.png", :border => 0)%>


             <% else %>
             <br 
              <ul class="nav nav-list">
                <%= form_for :tweet, url: tweets_path, remote:true,  method: :post do |f| %>
                <%= f.text_area :message , :maxlength => 140 %>
                <!--%= f.text_area :message, :maxlenght => 40 %-->

                   
                  <div class="brighten pic">
                  <%= image_submit_tag ('tweet-button.png') %>

                   </div>

                 
                    <% end %>

               <% end %>

              </ul>
            </div><!--/.well -->



            </div>
    



            <div class="well sidebar-nav">
              
                

            
            </div><!--/.well -->
         <div class="well sidebar-nav">
              <h3>playlist</h3>
              </ul>
            </div><!--/.well -->
      </div><!--/span-->
 
       </div>
          

    